/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nebulaera_myjnitest_HelloWorld */

#ifndef _Included_com_nebulaera_myjnitest_HelloWorld
#define _Included_com_nebulaera_myjnitest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nebulaera_myjnitest_HelloWorld
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nebulaera_myjnitest_HelloWorld_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
